---
title: Dissertation Sims
output: pdf_document
---
## EPSG:32617
## WGS 84 / UTM zone 17N

```{r initialize_environment, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, echo = FALSE, message = FALSE)
library(tidyverse)
library(tidycensus)
library(sf)
library(rSPDE)
library(INLA)

library(terra)
library(stars)
library(partykit)
library(rmarkdown)
library(knitr)
## library(onion)
library(spatstat)
library(fmesher)
library(compositions)
library(mgcv)

library(optimParallel)
```

Geodata
```{r}

counties <- read_rds('data/countyfiles.rds')



label_roads <- function(road_code) {
    case_when(
        road_code == 'S1100' ~ 'Primary Road',
        road_code == 'S1200' ~ 'Secondary Road',
        road_code == 'S1400' ~ 'Local Road',
        road_code == 'S1630' ~ 'Omit', #ramp
        road_code == 'S1640' ~ 'Omit', # 'service drive'
        road_code == 'S1710' ~ 'Omit', #walkway
        road_code == 'S1720' ~ 'Omit', #stairway
        road_code == 'S1730' ~ 'Omit', #alley
        road_code == 'S1740' ~ 'Omit', #service road'
        road_code == 'S1750' ~ 'Omit', #census internal
        road_code == 'S1780' ~ 'Omit', #parking
        road_code == 'S1820' ~ 'Omit', #bike path'
        road_code == 'S1500' ~ 'Omit' #vehicular trail
    )
}
    roads <- read_rds('data/roadfiles.rds')


roads <- roads |>
    mutate(type = label_roads(MTFCC)) |>
    filter(type != 'Omit') |>
    st_simplify()
    


```


Compositional Data
```{r, include = FALSE}

census_variables <- read_rds('data/census_variables.rds')
population <- read_rds('data/population.rds') |> select(geoid = GEOID, name = NAME,  population = value)

racecomp <- read_rds('data/decennial_race.rds') |>
    left_join( census_variables, by = c('variable' = 'name')) |>
    mutate(
        one_race = str_detect(label, "Population of one race"),
        race = case_when(
            label == "Total!!Population of one race!!White alone"  ~ "White",
            label == "Total!!Population of one race!!Black or African American"  ~ 'Black',
            TRUE ~ 'Other')
        ) |>
    select(geoid = GEOID, name = NAME, race, value) |>
    group_by(geoid, name, race) |>
    summarize(value = sum(value, na.rm = TRUE)) |>
    ungroup() |>
    mutate(
        value = if_else(is.na(value), 0L, value),
        value = value + 1L) |>
    group_by(geoid) |>
    mutate(
        prop = value / sum(value)) |>
    arrange(race, .by_group = TRUE)

splits <- with(racecomp, split(prop, geoid))
ilrb <- ilrBase(splits[[1]])
comps <- lapply(splits, function(x) ilr(x, ilrb))

racecompfinal <- racecomp |> select(geoid, name) |> distinct() |>
    ungroup() |>
    mutate(comps = comps)


point <- st_centroid(data[example,])

ggplot() + scale_fill_viridis_c() +
    geom_sf(aes(fill = dist_from), data = datat) +
    geom_sf(data = point, size = 2) |>
```

Weather and Air
```{r}

weather <- read_rds('data/weather.rds')
pm25 <- read_rds('data/pm25_cube.rds')
## data/epa_data_HAPS.rds
## data/epa_data_Lead.rds
## data/epa_data_No2.rds
## data/epa_data_NONOxNOy.rds
## data/epa_data_Ozone.rds
## data/epa_data_PM10_mass.rds
## data/epa_data_PM10_species.rds
## data/epa_data_PM25_frm_fem_mass.rds
## data/epa_data_PM25_species.rds
## data/epa_data_SO2.rds
## data/epa_data_VOC.rds
```

Fracking
```{r}

```


```{r, include = FALSE}

d <- filter(d, lon > -91, lon < -90, lat < 41, lat > 40)

r <- d$GWRPM25
y <- c(r)
co <- st_coordinates(d)
dd <- bind_cols(co, y = y)

fit <- gam(y ~ s(lon, lat, bs = 'gp', m = 5), data = dd)
r2y <- predict(fit)
r2 <- r
r2[!is.nan(r2)] <- r2y

par(mfrow = c(3,1))
image(r)
image(r2)
image(r - r2)

fit <- lmtree(y ~ lon + lat | lon + lat, data = dd)
p <- predict(fit, newdata = dd)

r3 <- r2
r3[] <- p
image(r3)

resid <- r - r3

fit <- gam(y ~ s(lon, lat, bs = 'gp', m = 5), data = mutate(dd, y = c(resid)))

p2 <- predict(fit, newdata = dd)


## loc_2d_mesh = co
## mesh_2d = inla.mesh.2d(
##   loc=loc_2d_mesh,
##   cutoff=0.05,
##   max.edge=c(0.1,0.5) )


## Abar <- rspde.make.A(mesh = mesh_2d, loc = as.matrix(loc_2d_mesh))
## mesh.index <- rspde.make.index(name = 'field', mesh = mesh_2d)

## st.dat <- inla.stack(
##   data = list(y = as.vector(r)),
##   A = Abar,
##   effects = mesh.index)


## rspde_model <- rspde.matern(mesh = mesh_2d, nu_upper_bound = 1)


## f = y ~ -1 + f(field, model = rspde_model)
## ## inla currently not working
## ## rspde_fit <- inla(f, data = inla.stack.data(st.dat),
##                   ## family = 'gaussian',
##                   ## control.predictor = list(A = inla.stack.A(st.dat)),
## ## inla.mode = 'experimental', verbose = TRUE)

mlik <- function(theta, Y, A, op) {
  sigma = exp(theta[1])
  kappa = exp(theta[2])
  nu = exp(theta[3])
  return(-rSPDE::rSPDE.matern.loglike(object = op,
                                      Y = Y,
                                      A = A,
                                      user_kappa = kappa,
                                      user_sigma = sigma,
                                      user_nu = nu, sigma. = exp(theta[4])))
}

loc_2d_mesh = co[!is.nan(y), ]
y <- y[!is.nan(y)]
mesh_2d = inla.mesh.2d(
  loc=loc_2d_mesh,
  cutoff=0.05,
  max.edge=c(0.1,0.5) )



n_cores <- parallel::detectCores() - 1
cl <- makeCluster(n_cores)

setDefaultCluster(cl = cl)
sigma <- 1
range <- 0.2
nu <- 0.5
kappa <- sqrt(8*nu)/range
op <- matern.operators(mesh=mesh_2d,nu=nu,
                                   kappa=kappa,sigma=sigma,m=2)

theta0 = c(get.inital.values.rSPDE(mesh = mesh_2d),
           log(0.1 * sqrt(var(as.vector(y), na.rm = TRUE))))

A <- inla.spde.make.A(
  mesh=mesh_2d,
  loc=as.matrix(loc_2d_mesh))

sigma.e <- 0.1
pars <- optimParallel(theta0, mlik, Y = y, A = A, op = op)
results <- data.frame(sigma = exp(pars$par[1]), 
                      kappa =  exp(pars$par[2]),
                      nu = exp(pars$par[3]),
                      sigma.e = exp(pars$par[4]),
                      row.names = "Estimate")


predgrid <- inla.mesh.projector(mesh_2d, xlim = c(0,1), 
ylim = c(0,1))
A.prd2 <- predgrid$proj$A


sigma.e.est <- exp(pars$par[4])
op.prd <- update(op, user_sigma = exp(pars$par[1]),
                 user_kappa = exp(pars$par[2]),
                 user_nu = exp(pars$par[3]))

pred.rspde <- predict(op.prd, A = A, Aprd = A, Y = y, 
                      sigma.e = sigma.e.est,
                      compute.variances = TRUE)
rp <- r
rp[!is.nan(r)] <- pred.rspde$mean

```


```{r}

dmap <- read_rds('R/simulation_utilities/allegheny_region_tracts.rds')

## sample code for generating the fem object

topo <- dmap |> st_make_valid() |> 
  group_split(id) |> map(st_union) |> 
  map_dfr(st_as_sf)

t1 <- st_as_sfc(topo[1,])

## pa coords--40.4406° N, 79.9959° W
t1 <- st_transform(t1, "EPSG:3857") |> st_simplify(dTolerance = 200)


# create mesh
edge <- st_buffer(t1, 3000)
me <- fm_mesh_2d(boundary = edge, interior = t1, max.edge = 2500)

Amat <- inla.spde.make.A(me)
#fm_basis

spde_mod <- inla.spde2.matern(me, alpha = 2)





#compositional covars

## kernel_sim
source('outcome_models.R')

x <- swedishpines
kern <- function(x,y) exp(-5 * sqrt((x^2 + y^2)))
xe <- as.im(x)
ts <- seq(from = -1, to = 1, length.out = 256)
t2 <- seq(from = -2, to = 2, length.out = 256 * 2)
km <- (outer(t2, t2, kern))

zero_pad <- matrix(0, nrow = 256 * 2, ncol = 256 * 2)

f1 <- zero_pad
f1[1:256, 1:256] <- as.matrix(as.im(x, dimyx = 256))
f1 <- fft(f1)

f2 <- fft(apply(apply(km, 1, fftshift), 1, fftshift))


resurf <- fft(f1 * f2, inverse = TRUE) / prod(dim(f1))
resurf <- Re(resurf)[1:256, 1:256]
image(resurf)



y <- c(resurf) + rnorm(length(resurf))

ym <- matrix(y, nrow = 256, 256)
yf <- as.function.im(as.im(ym, window(swedishpines)))
Q <- quadscheme(swedishpines)

dat <- mpl_prepare(swedishpines, quadscheme(swedishpines), ppcov = list(x), dimyx = c(128, 128))

qc <- coords(Q)
yy <- yf(qc[,1], qc[,2])

dat$yy <- yy
fit <- gam(yy ~ s(`...5`, bs = 'conv') - 1, data = dat)

basis <- smoothCon(s(`...5`, bs = 'conv'), data = dat, absorb.cons = TRUE)
basis <- basis[[1]]$X

dat$fitted <- fitted(fit)

smooths <- fit$smooth

smooth_internal <- smooths[[1]]$internal_basis

XX <- PredictMat(smooth_internal, data.frame(distances = seq(from = 0, to = 3, length.out = 400)))

plot(XX[,2:10] %*% coef(fit))

```


```{r, include = FALSE}


## four phases
## well_pad prep
## drilling
## fracturing
## production

spud <- read_rds('data/spud.rds')
production <- read_rds('data/production.rds')
select(well_permit_num,
       reporting_period,
           production_indicator,
           waste_indicator,
           well_status,
           spud_date,
           gas_quantity,
           gas_production_days,
           averaged,
           well_latitude,
           well_longitude,
           well_type,
           unconventional) |>
    filter(unconventional == 'Yes') |>
    select(!unconventional)

```

#####################
## BASIC DATA PREP ##
#####################

*Sim 1 block
```{r}
## for all simulations we will use the basic map of allegheny county
allegheny <- read_rds('R/simulation_utilities/allegheny_region_tracts.rds') |>
    mutate(region = id, id = row_number())
allegheny <- st_make_valid(allegheny)
allegheny <- st_transform(allegheny, '+proj=aeqd +lon_0=-79.3212891 +lat_0=40.2041883 +datum=WGS84 +units=m +no_def')


ggplot(allegheny) + geom_sf(aes( fill = region))

covering_grid <- st_make_grid(allegheny, n = c(20, 20))
gg <- st_intersection(covering_grid, allegheny)


alltess <- map(allegheny$geometry, as.owin) |> tess(tiles = _)

window <- as.owin(allegheny)

## generate point process valued outcome with confounding by covariates for basic binary exposure.
## for simulation 1 we consider a simple, spatially located binary treatment with a non-confounding covariate

alltessf <- as.function(alltess)
set.seed(12)

treatment_center <- runifpoint(1, window)
treat_dist <- distfun(treatment_center)

treatmentfun <- function(x,y) treat_dist(x,y) < 12000
treatment <- as.im.function(treatmentfun, window)


covar_values <- rnorm(nrow(allegheny))
covarfun <-function(x,y) covar_values[as.numeric(alltessf(x,y))]
covar <- as.im.function(covarfun, window)


## the intercept term is specified as the expected number of points with treatment and covariate set to 0
## to get a reasonable and roughly controllable process it is best to set this term manually as log(N /area(w))
## where N is the expected number of points for the "neutral" process and area is the area of the observation window
```

Sim 1
* Sim1
```{r, sim1}
#######################
## BINARY TREATMENTS ##
#######################

intercept <- log(100 / area(window))
intens <- function(x,y) exp(covarfun(x,y) * 2 + treatmentfun(x,y) + intercept)
intens_im <- as.im(intens, window)
pp <- rpoispp(intens_im)

ppm(pp ~ covar + treatment)
ppm(pp ~ covar + treatment + s(x,y, k = 40, bs = 'gp'), use.gam = TRUE)

ppm(pp ~ treatment + s(x,y, k = 40, bs = 'gp'), use.gam = TRUE)
glmdata <- getglmdata(ppm(pp ~ alltessf + treatment))

ff <- glm(.mpl.Y ~ treatment + alltessf, weights = .mpl.W, data = glmdata, family = poisson())

plot(treatment)
```

Sim 2
* Sim2
```{r, sim2}
## simulation 2
## pointwise binary exposure, including covariates, but not confounding
## pointwise on the fine 128 by 128 grid used for computation
## technically this is still blockwise, but for small blocks

treatment2 <- rbinom(128 * 128, size = 1, prob = 0.5)
treatment2 <- matrix(treatment2, 128, 128)
treatment2 <- as.im(treatment2, window)

plot(treatment2)

intens <- exp(intercept + treatment2 + covar)
pp <- rpoispp(intens)
ppm(pp ~ treatment2 + covar)
```

Sim 3
* Sim3
```{r, sim3}
## simulation3
## binary random field exposure
## generated from matern random field and then clipped on the basis of being greater or lower than zero
gridx <- seq(from = 0, to = 1, length.out = 128)
treatment3 <- as.im(as.matrix(RFsimulate(RMmatern(var = 2, scale = 0.3, nu = 1.3), gridx, gridx)) > 0, window)

plot(treatment3)

intens <- exp(intercept + treatment3 + 0.1 * covar)

plot(intens)
pp <- rpoispp(intens)
fit <- ppm(pp ~ treatment3 + covar, use.gam = TRUE)
fit <- ppm(pp ~ treatment3 + covar + s(x,y, bs = 'gp', k = 40),  use.gam = TRUE)
```

*Sim 4 block
```{r}
## simulation 4, binary exposure with lower degree of spatial autocorrelation
treatment4 <- as.im(as.matrix(RFsimulate(RMmatern(var = 2, scale = 0.05, nu = 1.3), gridx, gridx)) > 0, window)

plot(treatment4)

intens <- exp(intercept + treatment4 + 0.1 * covar)
pp <- rpoispp(intens)
fit <- ppm(pp ~ treatment4 + covar, use.gam = TRUE)
fit <- ppm(pp ~ treatment4 + covar + s(x,y, bs = 'gp', k = 40),  use.gam = TRUE)
dd <- getglmdata(fit)
fit <- gam(.mpl.Y ~ treatment4 + covar + te(x,y, bs = 'gp', k = 10), weights = .mpl.W, data = dd, family = poisson())


treatment5 <- as.im(as.matrix(RFsimulate(RMmatern(var = 2, scale = 0.001, nu = 1.3), gridx, gridx)) > 0, window)

intens <- exp(intercept + treatment5 + 0.1 * covar)
pp <- rpoispp(intens)
fit <- ppm(pp ~ treatment5 + covar, use.gam = TRUE)
fit <- ppm(pp ~ treatment5 + covar + s(x,y, bs = 'gp', k = 40),  use.gam = TRUE)
dd <- getglmdata(fit)
fit <- gam(.mpl.Y ~ treatment5 + covar + te(x,y, bs = 'gp', k = 10), weights = .mpl.W, data = dd, family = poisson())
```
## simulation structure

*Sim 5 block
```{r}
## next round of simulations
## consider scenarios where covariates are themselves spatially autocorrelated, so there is residual spatially determined confounding.
spatial_covar <- as.im(as.matrix(RFsimulate(RMmatern(var = 2, scale = 0.1, nu = 1.3), gridx, gridx)), window)
intens <- exp(intercept + treatment3 + spatial_covar)



pp <- rpoispp(intens)
fit <- ppm(pp ~ treatment3 + spatial_covar, use.gam = TRUE)
fit <- ppm(pp ~ treatment3)
fit <- ppm(pp ~ treatment3 +  s(x,y, bs = 'gp', k = 40),  use.gam = TRUE)


```

Sim 6
* Sim4
```{r}
## explicitly confounded treatment on the basis of spatially autocorrelated covariate
treatment6 <- as.im(matrix(rbinom(128^2, 1, plogis(c(as.matrix(spatial_covar)) * 0.3 - 1)), 128, 128), window)

plot(treatment6)

plot(spatial_covar)

intens <- exp(intercept + treatment6 + spatial_covar)
pp <- rpoispp(intens)

fit <- ppm(pp ~ treatment6,  use.gam = TRUE)
fit <- ppm(pp ~ treatment6 +  spatial_covar,  use.gam = TRUE)
fit <- ppm(pp ~ treatment6 +  s(x,y, bs = 'gp', k = 40),  use.gam = TRUE)
```

Sim 7
* Sim5
```{r}
## treatment 7 is a spatially autocorrelated treatment resulting counfounded by a spatially autocorrelated covariate,
## but that is realized as a direct sum of the covariate and a secondary random process.
## as a result, this treatment has additional spatial autocorrelation and is 'clumpy'
residual_process <- RFsimulate(RMmatern(1.2, var = 0.8, scale = 0.7), gridx, gridx)
treatment7t <- as.im(as.matrix(residual_process), window) + spatial_covar
treatment7t <- as.function(treatment7t)
treatment7 <- function(x,y) treatment7t(x,y) >0
treatment7 <- as.im(treatment7, window)

plot(treatment7)
plot(spatial_covar)


intens <- exp(intercept + treatment7 + spatial_covar)
pp <- rpoispp(intens)

fit <- ppm(pp ~ treatment7,  use.gam = TRUE)
fit <- ppm(pp ~ treatment7 +  spatial_covar,  use.gam = TRUE)
fit <- ppm(pp ~ treatment7 +  s(x,y, bs = 'gp', k = 40),  use.gam = TRUE)

```

Sim 8
* Sim6
```{r}

## treatment8
## generate treatment as set of circles where circle centers are generated from a poisson process on the basis of the confounding covariate
set.seed(0)
pp_base <- spatial_covar - min(spatial_covar) + 1

## generate approximately 10 exposure centers
pp_base <- 10 * pp_base / integral(pp_base)

centers <- rpoispp(pp_base)

treat_surf <- distfun(centers)

treatment8 <- as.im(as.function(function(x,y) treat_surf(x,y) < 5000), window)

plot(treatment8)

intens <- exp(intercept + treatment8 + spatial_covar)
pp <- rpoispp(intens)

fit <- ppm(pp ~ treatment8,  use.gam = TRUE)
fit <- ppm(pp ~ treatment8 +  spatial_covar,  use.gam = TRUE)
fit <- ppm(pp ~ treatment8 +  s(x,y, bs = 'gp', k = 40),  use.gam = TRUE)
```
###########################
## CONTINUOUS TREATMENTS ##
###########################
* Sim7
```{r}
## treatment is spatial covar plus a residual surface

treatment9 <- as.im(treatment7t, window)

residual_process_noisy <- RFsimulate(RMmatern(1.2, var = 0.8, scale = 0.7) + RMnugget(var = 0.3), gridx, gridx)
treatment10t <- as.im(as.matrix(residual_process_noisy), window) + spatial_covar
plot(as.im(treatment10t, window))
plot(treatment9)
intens <- exp(intercept + treatment9 + spatial_covar)
pp <- rpoispp(intens)

fit <- ppm(pp ~ treatment9,  use.gam = TRUE)
fit <- ppm(pp ~ treatment9 +  spatial_covar,  use.gam = TRUE)
fit <- ppm(pp ~ treatment9 +  s(x,y, bs = 'gp', k = 40),  use.gam = TRUE)


## realistic and potentially advantageous scenario
## we have a continuous treatment generated as a function of space, but spatial confounders have discontinuities due to geographical features
sim_surface <- function(){
    im <- as.function(as.im(as.matrix(RFsimulate(RMmatern(nu = 1, var = 2, scale = 1), gridx, gridx))))

}
s <- map(1:4, ~sim_surface())
## determine data generation mechanism
## pick optimal model from candidate model set according to specified criteria
## calculate truth value of specified estimand under dgp
## generate data
## calculate estimator values on data

## aggregate estimator values
## calculate summary statistics on estimators
## combine summary statistics across simulations for comparisons

indexer <- function(x,y) allegheny$region[as.numeric(alltessf(x,y))]
indexed <- as.im(indexer, window)

partials <- map(1:4, function(i)as.im(function(x,y) s[[i]](x,y) * (indexer(x,y) == i), window))
broken_covar <- reduce(partials, `+`)

plot(broken_covar)

```

* Sim8
```{r}


set.seed(34)
source('outcome_models.R')

## swedishpines <- murchison$gold

## swedishpines <- shift(swedishpines, -c(352782.9, 6699742))


## it appears there's some sort of interpolation bug due to window scale going on that results in covariates not scaling properly.
## may also have something to do with distance calculations
myexposure <- rescale(swedishpines, c(10))
## myexposure <- redwood
## myexposure <- rescale(redwood, 0.67)

## myexposure <- swedishpines
exp_im <- (as.matrix(as.im(myexposure)))
kernx <- seq(from = -12, to = 12, length = 128 * 2)
kern <- fft2shift(outer(kernx, kernx, function(x,y) exp(- x ^2 - y^2)))

exp_imb <- matrix(0, nrow = 256, ncol = 256)
exp_imb[1:128, 1:128] <- exp_im


exp_im <- Re((fft(fft(exp_imb) * fft(kern), inverse = TRUE) / 256^2))[1:128, 1:128]
## intens_surface <- as.im(exp_im / 100, W = myexposure$window)
intens_surface <- as.im(exp_im * 10, W = myexposure$window)



## dd <- dd |> mutate(mytreatment = treatcov)
make_summary_plot <- function(model, intens, newpoints){

    
    plot_data <- mutate(newpoints,
                        pred = predict(model, newpoints, type = 'response'),
                        truth = interp.im(intens, newpoints),
                        res = truth - pred
                        ) 

    plot_data |>
        pivot_longer(c(truth, res, pred), names_to = 'plot', values_to = 'value') |>
        ggplot(aes(x, y, fill = value)) + geom_raster() + facet_wrap(~plot) + scale_fill_viridis_c()
}




mytreatment <- (intens_surface > median(intens_surface))



treated_intens_surface <- exp(log(intens_surface))
myoutcome <- (rpoispp(lambda = treated_intens_surface))
nd <- 200
q <- quadscheme(myoutcome, nd = nd)
mydummy <- as_tibble(coords(q$dummy))
mydd <- mydummy |>
    slice(-((nrow(mydummy) - 3):nrow(mydummy)))



fit2 <- ppmod(myoutcome, q, ppcov = list(myexposure = myexposure), k = 40)
mydd2 <- mutate(mydd, mytreatment = mytreatment[list(x = x, y = y)])
make_summary_plot(fit2, treated_intens_surface, mydd2)


## show visual outcome model in basic model, including other covariates
# outcome model estimation




```
