#+STARTUP: overview
* Basic MCMC
#+BEGIN_SOURCE R
set.seed(12)


prior <- function(theta) dbeta(theta, 1,1)
likelihood <- function(theta, n) dbinom(n, size = 20, prob = theta)
observed <- 14
P <- function(theta, n) prior(theta) * likelihood(theta, n)
N <- 20000

samples <- vector(mode = "numeric", length = N)
accepted <- vector(mode =  "numeric", length = N)
samples[1] <- 0.5


run_sampler <- function(sd) {
  start <- Sys.time()
  for (i in 1:(N-1)) {
    current <- samples[i]
    proposal <- current + rnorm(1, 0, sd)
    p_accept <- ifelse(proposal > 1 | proposal < 0, 0, P(proposal, observed) / P(current, observed))
    accepted[i] <- ifelse(p_accept > 1, 1, rbinom(1,1, p_accept))
    samples[i+1] = ifelse(accepted[i], proposal, current)
  }
  end <- Sys.time()
  cat(end - start)
}
run_sampler(0.2)


#+END_SOURCE
* Bind to Environment
#+BEGIN_SOURCE R


## rlang::env_unlock(env = alpaca)
## rlang::env_binding_unlock(env = alpaca)
## assign('biasCorr_new', biasCorr_new, envir = alpaca)
## rlang::env_binding_lock(env = alpaca)
## rlang::env_lock(env = alpaca)
## biasCorr_new <- alpaca:::biasCorr_new

## unlockBinding('biasCorr_new', alpaca)
## assignInNamespace('biasCorr_new', biasCorr_new,ns = 'alpaca', envir = alpaca)
## assign('biasCorr_new', biasCorr_new, envir = alpaca)
## lockBinding('biasCorr_new', alpaca)

environment(biasCorr_new) <- asNamespace('alpaca')

#+END_SOURCE
* Basic IPW/AIPW
#+BEGIN_SOURCE R
library(tidyverse)

n <- 5000
z <- rnorm(n)
x <- rnorm(n) + 0.2 * z
treat <- rbinom(n, 1, plogis(-1 + 2 * z))

y <- 1 + 0.3 * x + 2 * treat + rnorm(n, 0.15)
d <- tibble(x, y, treat, z)
mean_fit <- lm(y ~ x + treat, data = d)
mu1 <- predict(mean_fit, mutate(d, treat = 1 ))
mu0 <- predict(mean_fit, mutate(d, treat = 0))

## for the linear regression model conditioned on the correct covariates
## the ATE estimate is equivalent to the mean prediction difference between the
## predicted response under treatment and not under treatment for all individuals
reg <- mean(mu1 - mu0)
reg_coef <- coef(mean_fit)[[3]]
## for the model with no heterogeneity this is also equivalent to the treatment coefficient
reg == reg_coef

mean_fit_int <- lm(y ~ x * treat, data = d)

mu1i <- predict(mean_fit_int, mutate(d, treat = 1 ))
mu0i <- predict(mean_fit_int, mutate(d, treat = 0))

## for the model with interactions this no longer holds
## the ate is now the average difference. In this particular case it is still very close since the interaction term is exactly zero
ireg <- mean(mu1i - mu0i)

## this can be extended to entirely separate models for treatment and non-treatment, each predicted on the whole dataset

mu1ii <- predict(lm(y ~ x,
                    data = filter(d, treat == 1)),
                 mutate(d, treat = 1 ))
mu0ii <- predict(lm(y ~ x,
                    data = filter(d, treat == 0)),
                 mutate(d, treat = 0))

ate_ii <- mean(mu1ii - mu0ii)




## propensity score type methods develop a different approach

treat_fit <- glm(treat ~ z, data = d, family = binomial())

## for example conditioning on the propensity score of treatment
## is equivalent to conditioning on covariates for estimating the ATE
## It is numerically different, but provides identification

## propensity score matching is another option (not shown yet)

pi1 <- predict(treat_fit, mutate(d, treat = 1), type = 'response')
lm(y ~ treat + splines::ns(pi1, 5))


## alternatively ipw estimators treat this more directly as a missing data type problem
## for the ipw estimator we generate the ipw estimate of the mean of Y_1, treating the Y_0 as missing
## and further separately generate the ipw estimate of the mean of Y_0, treating the Y_0 as missing
## The difference of these two is the ATE

## there exists multiple options. There is the naive horvitz thompson type estimator in which the denominator is simply the overall mean
pi0 <- 1 - pi1
ipw <- mean(y * treat /pi1 - y * (1 - treat) / pi0)

## and there is the normalized ipw estimator that can be obtained through
## dividing by the sum of weights in the denominator
ipwn1 <- (sum(y * treat / pi1)) / sum(treat / pi1)
ipwn0 <- (sum(y * (1 - treat) / pi0)) / sum((1 - treat) / pi0)
ipwn <- ipwn1 - ipwn0

## finally we get the Augmented-ipw estimator
## This generates separate estimators for Y_1 and Y_0 as in the ipw case
## it does this through a complex function combining predicted averages from the mean model, with weights predicted by the treatment assignment model
## The aipw for each term takes the average from the mean model, with a correction term subtracted out. Where the correction term is an inverse weighted deviation from the mean

aipw1 <- mean(mu1 + (y - mu1) * treat / pi1)
aipw0 <- mean(mu0 + (y - mu0) * (1 - treat) / pi0)
aipw <- aipw1 - aipw0

## The aipw estimator is alternatively algebraically equivalent to a version
## more closely resembles a corrected ipw estimator
## instead of a corrected regression estimator
aipw1 <- mean(y * treat / pi1 - ((treat - pi1) / pi1) * mu1)
aipw0 <- mean(y * (1 - treat) / pi0 - (((1 -treat) - pi0) / pi0) * mu0)

library(spatstat)

win <- owin(c(-1, 1), c(-1, 1))
beta <-t( t(rnorm(6)))
beta2 <- t(t(rnorm(6)))

treatment_link <- function(x,y) cbind(1, x, y, x^2, y^2, x * y) %*% beta
treatment_mu <- function(x,y) plogis(treatment_link(x,y))
treatment <- function(x,y) rbinom(length(x), 1, prob = treatment_mu(x,y))
confound <- function(x,y) cbind(1, x, y, x^2, y^2, x * y) %*% beta2

treatment <- as.function(as.im(treatment, win))
confound <- as.function(as.im(confound, win))

p <- process <- rpoispp(function(x,y) exp(2 + 2 * treatment(x,y) + confound(x,y)), win = win)

tt <- as.im(treatment)

for_reg <- mutate(expand_grid(x = tt$xcol, y = tt$yrow), v = c(tt$v))

prop_fit <- glm(v ~ poly(x,y, degree = 2), data = for_reg, family = binomial())

prop <- predict(prop_fit, type = 'response')
vv <- tt$v

vv[] <- prop
propensity_score <- tt
propensity_score$v <- vv
outcome <- ppm(p ~ treatment +poly(x,y, degree = 2))


tt_new = as.im(1, win)
new <- list(treatment = tt_new)
mu <- predict(outcome, type = 'intensity', covariates = new)
new <- list(treatment = tt_new - 1)
mu2 <- predict(outcome, type = 'intensity', covariates = new)

Y <- as.im(p)
a <- c(tt$v)

## looks correct
## first term is integration with respect to intensity measure, i.e. the expectaiton.
# second term is integration with respect to residual measure, i.e. 
y <- integral(mu) + sum(tt * Y / propensity_score) - integral(tt * mu / propensity_score)
y2 <- integral(mu2) + sum((1-tt) * Y / (1-propensity_score)) - integral((1-tt) * mu2 / (1-propensity_score))
#+END_SOURCE
* Basic Compositional
#+BEGIN_SOURCE R
library(tidyverse)
library(tidycensus)
library(sf)

d <- read_csv('~/Desktop/decennial_race_data/DECENNIALPL2020.P1_data_with_overlays_2021-12-20T114314.csv', skip = 1)
dr <- d %>% select(1:2, contains('Population of one race')) 

dr <- dr %>% select(!3)


library(compositions)

dr %>% pack(comp = c(3:8)) %>%
    mutate(comp = ilr(comp))
bg <- tigris::block_groups(state = 'PA')

bg <- bg %>% transmute(id = GEOID)
dr <- dr %>% mutate(id = str_extract(id, '(?<=US).+'))

dr <- dr %>% select(1, 2, 3, 4, 6, 8) %>% mutate(across(!c(1:2), ~ . + ))

dr <- dr %>% pack(comp = (3:6)) %>%
    mutate(comp = ilr(comp))
dr <- dr %>% mutate(comp = as.data.frame(comp)) %>%
    unpack(cols = comp)
dr <- dr %>% select(-2)

data <- inner_join(dr, bg)
data <- st_as_sf(data)

dd <- dist(select(as_tibble(data), V1, V2, V3))

dd <- as.matrix(dd)
example <- 1

datat <- data %>% mutate(dist_from = c(dd[example,]))

point <- st_centroid(data[example,])

ggplot() + scale_fill_viridis_c() +
    geom_sf(aes(fill = dist_from), data = datat) +
    geom_sf(data = point, size = 2)

#+END_SOURCE
* Basic Distmat Model
#+BEGIN_SOURCE R
library(spatstat)
library(tidyverse)
library(proxy)

obspoints <- coords(swedishpines)

xmin <- min(obspoints$x)
xmax <- max(obspoints$x)

ymin <- min(obspoints$y)
ymax <- max(obspoints$y)

point_grid <- expand_grid(x = seq(from = xmin-1, to = xmax + 1, length = 50),
                          y = seq(from = ymin - 1, to = ymax +1, length = 50))

dd <- function(x,y) sqrt(sum((x - y)^2))


distmat <- matrix(nrow = nrow(point_grid), ncol = nrow(obspoints))

for( i in 1:nrow(point_grid)) {
  for (j in 1:nrow(obspoints)) {
    distmat[i,j] <- dd(point_grid[i,],  obspoints[j,])
  }
}

alpha <- rnorm(71, mean = 23)
results <- apply(distmat, 1, function(x) sum(alpha *  exp(-x/12)))


library(splines)
bs1 <- ns(distmat[,1], 6)
gen_basis <- function(index) function(x) predict(bs1, x)[,index]
## bbasis <- function(a) function(x) exp(-a * x^2)
bases <- map(1:12, gen_basis)

true_dist <- apply(distmat, 1, mean)

dists <- map_dfc(bases, ~apply(distmat, 1, function(x) mean(.x( x))))

                 
pp <- point_grid %>% mutate(v = results) %>%
  bind_cols(dists) %>%
  mutate(true_dist = true_dist)

ff <- lm(v ~ . - x - y, data = pp)

pp <- mutate(pp, r = residuals(ff), p= predict(ff))
ggplot(pp, aes(x,y, fill = v)) + geom_raster() + scale_fill_viridis_c()

ggplot(pp, aes(x,y, fill = p)) + geom_raster() + scale_fill_viridis_c()

## this appears to be the correct approach
## this uses a finite basis approximation

## residual variation will be absorbed into the gaussian field random effect
ffbase <- gam(v ~ x4 + x5 + x6 + x7 + x8 + x9,data = pp)

## linear functional basis approximation
pp2 <- pp2 %>% mutate(dist  = as.matrix(distmat))
pp2 <- pp2 %>% mutate(xinter = reduce(rep(list(x), ncol(distmat)), cbind), yinter = reduce(rep(list(y), ncol(distmat)), cbind))

pp2 <- pp2 %>% mutate(xinter = as.matrix(xinter), yinter = as.matrix(yinter))
ffbase <- gam(v ~ s(dist), data = pp2)
ffbaseinter <- gam(v ~ s(dist) + s(xinter, yinter, by = dist, bs = 'gp', m = 4), data = pp2)


p <- predict(ffbaseinter)
r <- residuals(ffbaseinter)
mutate(pp, p = p, r = r) %>% ggplot(aes(x,y, fill = p)) + geom_raster() + scale_fill_viridis_c()


library(sp)
coordinates(pp) <- ~ x + y

library(gstat)

vv <- variogram(r ~ 1, data = pp)
plot(vv, fit.variogram(vv, vgm('Gau')))

library(mgcv)
pp <- as_tibble(pp)
pp <- janitor::clean_names(pp)
## this is a residual gaussian process term, not an interaction term

#+END_SOURCE
* Basic Random Fields Simulation
#+BEGIN_SOURCE R

library(RandomFields)

model <- RMbrownresnick(RMfbm(alpha=1.5, s=0.2))

model <- RMbessel(nu=2, scale=0.5)
## anisotropy 
angle <- RMangle(angle = pi, ratio = 1.3)
model <- RMwave( scale=0.1)
model <- RMexp(Aniso=RMangle(angle=pi/4, ratio = 12))
model <- RMmatern(nu = 1.9, var = 1, scale = 5)
nugget<-  RMnugget(var = 0.01)
## model terms can be added
model <- RMmatern(nu = 1.9, var = 1, scale = 5, Aniso = angle) + nugget + RMbessel(nu=2, scale=0.5) 

x.seq <- seq(from = 0, to = 20, length = 250)
y.seq <- x.seq

## 1d simulation
simu <- RFsimulate(model, x.seq)
## 2d simulation
simu <- RFsimulate(model, x.seq, y.seq)
simu <- RFsimulate(model, x.seq, y.seq
## also allows higher order simulation
plot(simu)



## starts by assuming a gaussian model generally RPGauss

model <- RMexp()
plot(RFsimulate(model, x.seq, y.seq))

## however other types of models can be simulate such as bernoulli fields
plot(RFsimulate(RPbernoulli(model), x.seq, y.seq))

model <- RMbessel(nu=2, scale=0.5)
plot(RFsimulate(RPbernoulli(model), x.seq, y.seq))

## t models
model <- RMexp()
mod <- RPt(model, nu = 1)
plot(RFsimulate(mod, x.seq, y.seq))

## chi2 type models
model <- RMexp()
mod <- RPchi2(model, f = 1)
plot(RFsimulate(mod, x.seq, y.seq))

## poisson shot noise
## not working
model <- RMexp()
mod <- RPpoisson(model, intensity = 1)
plot(RFsimulate(mod, x.seq, y.seq))

model <- RMexp()
mode <- RPcirculant

#+END_SOURCE
* Raster Fits
#+BEGIN_SOURCE R
library(tidyverse)
library(stars)
library(partykit)
d <- read_ncdf('~/Downloads/V5GL02.HybridPM25.NorthAmerica.201907-201907.nc')

d <- filter(d, lon > -91, lon < -90, lat < 41, lat > 40)

r <- d$GWRPM25
y <- c(r)
co <- st_coordinates(d)
dd <- bind_cols(co, y = y)
library(mgcv)
fit <- gam(y ~ s(lon, lat, bs = 'gp', m = 5), data = dd)
r2y <- predict(fit)
r2 <- r
r2[!is.nan(r2)] <- r2y

par(mfrow = c(3,1))
image(r)
image(r2)
image(r - r2)

fit <- lmtree(y ~ lon + lat | lon + lat, data = dd)
p <- predict(fit, newdata = dd)

r3 <- r2
r3[] <- p
image(r3)

resid <- r - r3

fit <- gam(y ~ s(lon, lat, bs = 'gp', m = 5), data = mutate(dd, y = c(resid)))

p2 <- predict(fit, newdata = dd)


library(rSPDE)
library(INLA)

## loc_2d_mesh = co
## mesh_2d = inla.mesh.2d(
##   loc=loc_2d_mesh,
##   cutoff=0.05,
##   max.edge=c(0.1,0.5) )


## Abar <- rspde.make.A(mesh = mesh_2d, loc = as.matrix(loc_2d_mesh))
## mesh.index <- rspde.make.index(name = 'field', mesh = mesh_2d)

## st.dat <- inla.stack(
##   data = list(y = as.vector(r)),
##   A = Abar,
##   effects = mesh.index)


## rspde_model <- rspde.matern(mesh = mesh_2d, nu_upper_bound = 1)


## f = y ~ -1 + f(field, model = rspde_model)
## ## inla currently not working
## ## rspde_fit <- inla(f, data = inla.stack.data(st.dat),
##                   ## family = 'gaussian',
##                   ## control.predictor = list(A = inla.stack.A(st.dat)),
## ## inla.mode = 'experimental', verbose = TRUE)

mlik <- function(theta, Y, A, op) {
  sigma = exp(theta[1])
  kappa = exp(theta[2])
  nu = exp(theta[3])
  return(-rSPDE::rSPDE.matern.loglike(object = op,
                                      Y = Y,
                                      A = A,
                                      user_kappa = kappa,
                                      user_sigma = sigma,
                                      user_nu = nu, sigma. = exp(theta[4])))
}

loc_2d_mesh = co[!is.nan(y), ]
y <- y[!is.nan(y)]
mesh_2d = inla.mesh.2d(
  loc=loc_2d_mesh,
  cutoff=0.05,
  max.edge=c(0.1,0.5) )


library(optimParallel)
n_cores <- parallel::detectCores() - 1
cl <- makeCluster(n_cores)

setDefaultCluster(cl = cl)
sigma <- 1
range <- 0.2
nu <- 0.5
kappa <- sqrt(8*nu)/range
op <- matern.operators(mesh=mesh_2d,nu=nu,
                                   kappa=kappa,sigma=sigma,m=2)

theta0 = c(get.inital.values.rSPDE(mesh = mesh_2d),
           log(0.1 * sqrt(var(as.vector(y), na.rm = TRUE))))

A <- inla.spde.make.A(
  mesh=mesh_2d,
  loc=as.matrix(loc_2d_mesh))

sigma.e <- 0.1
pars <- optimParallel(theta0, mlik, Y = y, A = A, op = op)
results <- data.frame(sigma = exp(pars$par[1]), 
                      kappa =  exp(pars$par[2]),
                      nu = exp(pars$par[3]),
                      sigma.e = exp(pars$par[4]),
                      row.names = "Estimate")


predgrid <- inla.mesh.projector(mesh_2d, xlim = c(0,1), 
ylim = c(0,1))
A.prd2 <- predgrid$proj$A


sigma.e.est <- exp(pars$par[4])
op.prd <- update(op, user_sigma = exp(pars$par[1]),
                 user_kappa = exp(pars$par[2]),
                 user_nu = exp(pars$par[3]))

pred.rspde <- predict(op.prd, A = A, Aprd = A, Y = y, 
                      sigma.e = sigma.e.est,
                      compute.variances = TRUE)
rp <- r
rp[!is.nan(r)] <- pred.rspde$mean

#+END_SOURCE
* Cartogram
#+BEGIN_SOURCE R
## failed attempt at cartogram code

                                        # get block by block data
#P001001 total population
library(tidycensus)
library(tidyverse)
library(cartogram)
library(sf)

pop <- "P001001"
pa_tract_data <- get_decennial(geography = "county", variables = pop, state = "PA", geometry = T) %>%
  select(county = NAME, county_population = value, geometry) %>%
  mutate(county = str_extract(county, "[A-Za-z]+")) %>%
  mutate(tract_data = map(county,
                          ~get_decennial(geography = "tract", county = ., state = "PA", variables = pop, geometry = T)))

pa_tract_data_full <- do.call(rbind, pa_tract_data$tract_data)


county_data <- select(pa_tract_data, -tract_data) %>%
  mutate(density = county_population / as.numeric(st_area(geometry)),
         weight = county_population) %>%
  st_transform(2271)
#  st_transform( "+proj=merc")

philly <- county_data %>% filter(county == "Philadelphia") %>% pull(geometry)
allegheny <- county_data %>% filter(county == "Allegheny") %>% pull(geometry)

county_data <- county_data %>%
  mutate(dist_philly = st_distance(st_centroid(geometry), st_centroid(philly)),
         dist_allegheny = st_distance(st_centroid(geometry), st_centroid(allegheny)))

closer_philly <- filter(county_data, dist_philly < dist_allegheny)
closer_allegheny <- filter(county_data, dist_allegheny < dist_philly)

ggplot(county_data) + geom_sf()

save(pa_tract_data_full, pa_tract_data, file = "pa_tract_data_full.rda")


county_data <- county_data %>% mutate(county = str_to_upper(county))

deaths <- preprocessed_data %>% filter(lat !=0, long != 0, !is.na(lat), !is.na(long)) %>%
  st_as_sf(coords = c('long', 'lat'))

death_sites <- deaths %>%
  select(county) %>%
  st_set_crs(4269) %>%
  st_transform(2271) %>%
  group_by(county) %>%
  summarize(geometry = st_combine(geometry))

county_data <- county_data %>% arrange(county)
death_sites <- death_sites %>% arrange(county)

data <- bind_cols(county_data, death_sites) %>%
  select(-county1) %>%
  mutate(id = row_number()) %>%
  group_by(id) %>%
  mutate(geometry = st_combine(c(geometry, geometry1)), geometry1 = NULL) %>%
  mutate(geometry = st_collection_extract(geometry, "POLYGON")) %>%
  ungroup()

pop_density_cartogram <- cartogram_cont(data, "density")
ggplot(pop_density_cartogram) + geom_sf() + theme_void()

#compute death rate per densit
#deaths_agg %>% left_join(pop) %>% mutate(rate = n / pop) %>% left_join(county_data %>% mutate(county = str_to_upper(county))) %>% mutate(rate_per_density = rate / density) -> death_data

#+END_SOURCE
* Empirical Derivative
#+BEGIN_SOURCE R
x <- rnorm(1000)

y <- rnorm(1000) + 2 + x
fit <- lm(y ~ x)

fit1 <- fit

## perturb model parameters for computing the estimating functions of the models
update.model <- function(model, index, delta) {
  fit <- model
  fit$coefficients[[index]] <- fit$coefficients[[index]] + delta
  fit$residuals <- y - predict(fit)
  fit
}

## after taking sample means of estimating functions, compute empirical derivatives

## could alternative compute sample derivatives before estimating mean. This might be more robust, but the former is required for non-smooth functions.
delta <- 0.001
d11 <- mean(estfun(fit1)[,1]) - mean(estfun(update.model(fit1, 1, delta))[,1]) / delta
d22 <- mean(estfun(fit1)[,2]) - mean(estfun(update.model(fit1, 2, delta))[,2]) / delta
d12 <- mean(estfun(fit1)[,1]) - mean(estfun(update.model(fit1, 2, delta))[,1]) / delta
d21 <- mean(estfun(fit1)[,2]) - mean(estfun(update.model(fit1, 1, delta))[,2]) / delta

## empirically calculated derivative is approximately equal to the actual one
br <- solve(matrix(c(d11, d21, d12, d22), ncol = 2))
bread(fit)



## poisson type model


## from https://ncss-wpengine.netdna-ssl.com/wp-content/themes/ncss/pdf/Procedures/NCSS/Negative_Binomial_Regression.pdf
## not correct, not sure why
## subsum <- function(y, alpha) {

##     summer <- function(singley, alpha) {
##             seq <- 1:(singley - 1)
##             sum(1 / (seq + (1 / alpha)))
##     }
##     summerv <- function(y, alpha) map_dbl(y, ~summer(., alpha))
##     if_else(y == 0, 0.0, summerv(y, alpha))
## }
## estfun_alpha <- function(alpha, mu, y) {
##     (1 / alpha^2) * (log(1 + alpha * mu) - subsum(y, alpha)) + (y - mu) / (alpha * (1 + alpha * mu))
## }

score <- function(n, th, mu, y, w) (w * (digamma(th + 
        y) - digamma(th) + log(th) + 1 - log(th + mu) - (y + 
                                                         th)/(mu + th)))

info_beta <- function(n, th, mu, y, w, x){
    -x * mu * 1/(th + mu) + 0.5 * mu * x * (y + th)/(mu + th)^2
}


info <- function(n, th, mu, y, w) (w * (-trigamma(th + 
        y) + trigamma(th) - 1/th + 2/(mu + th) - (y + th)/(mu + 
        th)^2))

nb_modified_fit <- function(form, data) {
    fit <-  glm(as.formula(form), family = poisson, data = data)

    mu <- predict(fit, type = 'response')
    fit_alpha <- MASS::glm.nb(y ~ offset(log(pred)) -1, data = mutate(data, pred = pred))

    alpha <- fit_alpha$theta
    w <- 1
    n <- nrow(data)
    est_alpha <- score(n, alpha, mu, data$y, w)
    est <- cbind(estfun(fit), est_alpha)

    mm <- model.matrix(fit)
    ## use the model matrix to get xs for computing the estimated bread matrix
    alpha_bread <- rep(0, ncol(mm) + 1)
    for(i in 1:ncol(mm)) {
        alpha_bread[i] <- sum(info_beta(n, alpha, mu, y, w, mm[,i]))
    }
    alpha_bread[length(alpha_bread)] <- sum(info(n, alpha, mu, y, w))
    bread <- cbind(rbind(cbind(solve(bread(fit)), 0), alpha_bread)) 
    bread <- solve(bread)
    meat <- crossprod(as.matrix(est)) / n
    vcov <- bread %*% meat %*% t(bread) / n
return(vcov)

}
library(lmtest)
library(sandwich)
sim_coverage <- function() {

    x <- rnorm(100)
    y <- rpois(100, exp(2 + x + rnorm(100, 0, 2)))
    d <- tibble(x, y)
    fit <- glm(y ~ x, family = poisson, data = d)

    nbmf <- nb_modified_fit(y ~x, data = d)
    se <- sqrt(nbmf[2,2])
    cinbmf <- c(coef(fit)[2] - 1.96 * se, coef(fit)[2] + 1.96 * se)
    cov_nbmf <- between(1, cinbmf[1], cinbmf[2])
    
    ci <- coefci(fit, 'x')
    cov_parametric <- between(1, ci[1], ci[2])
    ciS <- coefci(fit, 'x', vcov = vcovHC)
    cov_sandwich <- between(1, ciS[1], ciS[2])
    return(c(cov_parametric, cov_sandwich, cov_nbmf))
}
coverage <- map(1:100, ~sim_coverage())

mean(coverage %>% map_dbl(1))
mean(coverage %>% map_dbl(2))
mean(coverage %>% map_dbl(3))


#+END_SOURCE
* Mortgage Calculator
#+BEGIN_SOURCE R
library(tidyverse)
principal <- 240000
interest_rate_annual <- 2.625
payment_before <- 2000
payment_switch <- 72

payment_schedule <- tribble(
~payment, ~up_until,
1450, 3 * 12 + 6 ,
4500, 5 * 12 + 6,
5000, Inf
)


insurance_annual <- 1046
tax_annual <- 4800


remaining <- principal




sim <- function() {
    cum_payment <- 0
    principal <- principal

    num_months <- 30 * 12 + 6
for (month in 1:num_months) {

    payment <- payment_schedule$payment[first(which(month < payment_schedule$up_until))]
    cum_payment <- cum_payment + payment
    


  accrued <- principal * (interest_rate_annual / 100) / 12
  remaining <- remaining + accrued

  payment_to <- payment - insurance_annual / 12 - tax_annual / 12
  remaining <- remaining - payment_to
  principal <- remaining

  if (principal < 0) {
      cat(stringr::str_c('\n', month / 12 , ' years.\n'))
      cat(stringr::str_c('\n', cum_payment, 'total_payed\n'))
      break
     
  }

}
        return(remaining)
}



#+END_SOURCE
* Spatial Microsim
#+BEGIN_SOURCE R
library(tidyverse)
library(tidycensus)
library(assertr)
library(mipfp)


## load census variables for interactively finding correct variables
variables <- load_variables(year = 2010, 'acs5')
which_vars <- filter(variables, str_detect(name, 'B01001')) %>%
    slice(1:111) %>% pull(name) # filter down to black, white, and total

#county wide demographics data
data <- get_acs('county', which_vars, year = 2010, state = 'pa')

cleaned <- data %>% left_join(variables, by = c('variable' = 'name')) %>%
    mutate(sex = case_when(
               str_detect(label, 'Male') ~ 'Male',
               str_detect(label, 'Female') ~ 'Female',
               TRUE ~ 'Total'
           ),
           race = case_when(
               str_detect(concept, 'BLACK') ~ 'Black',
               str_detect(concept, 'WHITE') ~ 'White',
               TRUE ~ 'Total'
           ),
           age = str_extract(label, '(?<=(Male|Female)!!).+')
           ) %>%
    filter(sex != 'Total', !is.na(age)) %>%
    select(-label, -moe, -variable, -concept)

relabel_age <- function(age) {
    case_when(
        age %in% c('21 years', '20 years', '22 to 24 years') ~ '20 to 24 years',
        age %in% c('35 to 39 years', '40 to 44 years') ~ '35 to 44 years',
        age %in% c('45 to 49 years', '50 to 54 years') ~ '45 to 54 years',
        age %in% c('55 to 59 years', '60 to 64 years', '60 and 61 years', '62 to 64 years') ~ '55 to 64 years',
        age %in% c('65 and 66 years', '67 to 69 years', '70 to 74 years') ~ '65 to 74 years',
        age %in% c('75 to 79 years', '80 to 84 years') ~ '75 to 84 years',
        TRUE ~ age
    )
}

cleaned <- cleaned %>% mutate(age = relabel_age(age)) %>%
    group_by(GEOID, NAME, sex, race, age) %>%
    summarize(estimate = sum(estimate)) %>%
    ungroup() %>%
    spread(race, estimate) %>%
    mutate(Other = Total - (Black + White), Total = NULL) %>%
    verify(Other >= 0) %>%
    gather(race, estimate, Black, White, Other) %>%
    group_nest(GEOID, NAME) %>%
    rename(age_sex_race = data)


#tract by tract within county population estimates
tract_data <- get_acs(geography = 'tract', 'B01001_001', state = 'PA')

tracts <- tract_data %>%
    mutate(GEOID = str_sub(GEOID, 1, 5),
           variable = NULL) %>%
    select(-moe) %>%
    group_nest(GEOID) %>%
    rename(tract = data)

counties <- get_acs(geography = 'county', 'B01001_001', state = 'PA')

constraints <- full_join(tracts, cleaned)




int_trs <- function(xv){
    x <- as.vector(xv)
    xint <- floor(x)
    r <- x - xint
    def <- round(sum(r)) # the deficit population
                                        # the weights be 'topped up' (+ 1 applied)
    topup <- sample(length(x), size = def, prob = r)
    xint[topup] <- xint[topup] + 1
    dim(xint) <- dim(xv)
    dimnames(xint) <- dimnames(xv)
    xint
}


counties <- counties %>% mutate(ind_data = rep(list(NA), nrow(.)) )

for (i in seq_len(nrow(constraints))) {
    age_sex_race_names <- names(constraints[[i, 'age_sex_race']]) %>% discard(~.x == 'estimate')
    age_sex_race <- constraints[[i, 'age_sex_race']] %>% unite(age_sex_race, -estimate) %>% deframe

    tract_names <- names(constraints[[i, 'tract']]) %>% discard(~.x == 'estimate')
    tract <- constraints[[i, 'tract']] %>% unite(tract, -estimate) %>% deframe

    target <- list(age_sex_race, tract)
    seed <- array(1, map(target, length), map(target, names))
    weights <- suppressWarnings(Ipfp(seed, seq_along(target), target))
    weight_table <- as.data.frame.table(weights[[1]])
    expansion_counts <- int_trs(weight_table$Freq * counties[[i,'estimate']])
    indices <- rep(1:nrow(weight_table), expansion_counts)

    ind_data <- as_tibble(weight_table[indices, ]) %>%
        separate(Var1, into = age_sex_race_names, sep = '_') %>%
        separate(Var2, into = tract_names, sep = '_')

    counties$ind_data[i] <- list(ind_data)
}

dat_final <- counties %>% unnest() %>% select(sex, age, race, NAME, NAME1)







#+END_SOURCE
