# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

newfun <- function(c) {
    .Call(`_qoalapack_newfun`, c)
}

test <- function(h) {
    .Call(`_qoalapack_test`, h)
}

rcpp_hello_world <- function() {
    .Call(`_qoalapack_rcpp_hello_world`)
}

