---
output: html_document
---
```{r, include = FALSE}
library(RandomFields)
library(tidyverse)
library(sf)
library(spatstat)
knitr::opts_chunk$set(warning = FALSE, echo = FALSE, message = FALSE)
library(disslib)
```

#####################
## BASIC DATA PREP ##
#####################

Sim 1
```{r}
## for all simulations we will use the basic map of allegheny county
allegheny <- read_rds('simulation_utilities/allegheny_region_tracts.rds') |>
    mutate(region = id, id = row_number())
allegheny <- st_make_valid(allegheny)
allegheny <- st_transform(allegheny, '+proj=aeqd +lon_0=-79.3212891 +lat_0=40.2041883 +datum=WGS84 +units=m +no_def')


ggplot(allegheny) + geom_sf(aes( fill = region))

covering_grid <- st_make_grid(allegheny, n = c(20, 20))
gg <- st_intersection(covering_grid, allegheny)


alltess <- map(allegheny$geometry, as.owin)
alltess <- tess(tiles = alltess)

window <- as.owin(allegheny)

## generate point process valued outcome with confounding by covariates for basic binary exposure.
## for simulation 1 we consider a simple, spatially located binary treatment with a non-confounding covariate


alltessf <- as.function(alltess)
set.seed(12)

treatment_center <- runifpoint(1, window)
treat_dist <- distfun(treatment_center)

treatmentfun <- function(x,y) treat_dist(x,y) < 12000
treatment <- as.im.function(treatmentfun, window)


covar_values <- rnorm(nrow(allegheny))
covarfun <-function(x,y) covar_values[as.numeric(alltessf(x,y))]
covar <- as.im.function(covarfun, window)


## the intercept term is specified as the expected number of points with treatment and covariate set to 0
## to get a reasonable and roughly controllable process it is best to set this term manually as log(N /area(w))
## where N is the expected number of points for the "neutral" process and area is the area of the observation window
```

Sim 1

```{r, sim1}
#######################
## BINARY TREATMENTS ##
#######################

intercept <- log(100 / area(window))
intens <- function(x,y) exp(covarfun(x,y) * 2 + treatmentfun(x,y) + intercept)
intens_im <- as.im(intens, window)
pp <- rpoispp(intens_im)

ppm(pp ~ covar + treatment)
ppm(pp ~ covar + treatment + s(x,y, k = 40, bs = 'gp'), use.gam = TRUE)

ppm(pp ~ treatment + s(x,y, k = 40, bs = 'gp'), use.gam = TRUE)
glmdata <- getglmdata(ppm(pp ~ alltessf + treatment))

ff <- glm(.mpl.Y ~ treatment + alltessf, weights = .mpl.W, data = glmdata, family = poisson())

plot(treatment)
```

Sim 2

```{r, sim2}
## simulation 2
## pointwise binary exposure, including covariates, but not confounding
## pointwise on the fine 128 by 128 grid used for computation
## technically this is still blockwise, but for small blocks

treatment2 <- rbinom(128 * 128, size = 1, prob = 0.5)
treatment2 <- matrix(treatment2, 128, 128)
treatment2 <- as.im(treatment2, window)

plot(treatment2)

intens <- exp(intercept + treatment2 + covar)
pp <- rpoispp(intens)
ppm(pp ~ treatment2 + covar)
```

Sim 3

```{r, sim3}
## simulation3
## binary random field exposure
## generated from matern random field and then clipped on the basis of being greater or lower than zero
gridx <- seq(from = 0, to = 1, length.out = 128)
treatment3 <- as.im(as.matrix(RFsimulate(RMmatern(var = 2, scale = 0.3, nu = 1.3), gridx, gridx)) > 0, window)

plot(treatment3)

intens <- exp(intercept + treatment3 + 0.1 * covar)

plot(intens)
pp <- rpoispp(intens)
fit <- ppm(pp ~ treatment3 + covar, use.gam = TRUE)
fit <- ppm(pp ~ treatment3 + covar + s(x,y, bs = 'gp', k = 40),  use.gam = TRUE)
```

Sim 4
```{r}
## simulation 4, binary exposure with lower degree of spatial autocorrelation
treatment4 <- as.im(as.matrix(RFsimulate(RMmatern(var = 2, scale = 0.05, nu = 1.3), gridx, gridx)) > 0, window)

plot(treatment4)

intens <- exp(intercept + treatment4 + 0.1 * covar)
pp <- rpoispp(intens)
fit <- ppm(pp ~ treatment4 + covar, use.gam = TRUE)
fit <- ppm(pp ~ treatment4 + covar + s(x,y, bs = 'gp', k = 40),  use.gam = TRUE)
dd <- getglmdata(fit)
fit <- gam(.mpl.Y ~ treatment4 + covar + te(x,y, bs = 'gp', k = 10), weights = .mpl.W, data = dd, family = poisson())


treatment5 <- as.im(as.matrix(RFsimulate(RMmatern(var = 2, scale = 0.001, nu = 1.3), gridx, gridx)) > 0, window)

intens <- exp(intercept + treatment5 + 0.1 * covar)
pp <- rpoispp(intens)
fit <- ppm(pp ~ treatment5 + covar, use.gam = TRUE)
fit <- ppm(pp ~ treatment5 + covar + s(x,y, bs = 'gp', k = 40),  use.gam = TRUE)
dd <- getglmdata(fit)
fit <- gam(.mpl.Y ~ treatment5 + covar + te(x,y, bs = 'gp', k = 10), weights = .mpl.W, data = dd, family = poisson())
```
## simulation structure

Sim 5
```{r}
## next round of simulations
## consider scenarios where covariates are themselves spatially autocorrelated, so there is residual spatially determined confounding.
spatial_covar <- as.im(as.matrix(RFsimulate(RMmatern(var = 2, scale = 0.1, nu = 1.3), gridx, gridx)), window)
intens <- exp(intercept + treatment3 + spatial_covar)



pp <- rpoispp(intens)
fit <- ppm(pp ~ treatment3 + spatial_covar, use.gam = TRUE)
fit <- ppm(pp ~ treatment3)
fit <- ppm(pp ~ treatment3 +  s(x,y, bs = 'gp', k = 40),  use.gam = TRUE)


```

Sim 6

```{r}
## explicitly confounded treatment on the basis of spatially autocorrelated covariate
treatment6 <- as.im(matrix(rbinom(128^2, 1, plogis(c(as.matrix(spatial_covar)) * 0.3 - 1)), 128, 128), window)

plot(treatment6)

plot(spatial_covar)

intens <- exp(intercept + treatment6 + spatial_covar)
pp <- rpoispp(intens)

fit <- ppm(pp ~ treatment6,  use.gam = TRUE)
fit <- ppm(pp ~ treatment6 +  spatial_covar,  use.gam = TRUE)
fit <- ppm(pp ~ treatment6 +  s(x,y, bs = 'gp', k = 40),  use.gam = TRUE)
```

Sim 7

```{r}
## treatment 7 is a spatially autocorrelated treatment resulting counfounded by a spatially autocorrelated covariate,
## but that is realized as a direct sum of the covariate and a secondary random process.
## as a result, this treatment has additional spatial autocorrelation and is 'clumpy'
residual_process <- RFsimulate(RMmatern(1.2, var = 0.8, scale = 0.7), gridx, gridx)
treatment7t <- as.im(as.matrix(residual_process), window) + spatial_covar
treatment7t <- as.function(treatment7t)
treatment7 <- function(x,y) treatment7t(x,y) >0
treatment7 <- as.im(treatment7, window)

plot(treatment7)
plot(spatial_covar)


intens <- exp(intercept + treatment7 + spatial_covar)
pp <- rpoispp(intens)

fit <- ppm(pp ~ treatment7,  use.gam = TRUE)
fit <- ppm(pp ~ treatment7 +  spatial_covar,  use.gam = TRUE)
fit <- ppm(pp ~ treatment7 +  s(x,y, bs = 'gp', k = 40),  use.gam = TRUE)

```

Sim 8

```{r}

## treatment8
## generate treatment as set of circles where circle centers are generated from a poisson process on the basis of the confounding covariate
set.seed(0)
pp_base <- spatial_covar - min(spatial_covar) + 1

## generate approximately 10 exposure centers
pp_base <- 10 * pp_base / integral(pp_base)

centers <- rpoispp(pp_base)

treat_surf <- distfun(centers)

treatment8 <- as.im(as.function(function(x,y) treat_surf(x,y) < 5000), window)

plot(treatment8)

intens <- exp(intercept + treatment8 + spatial_covar)
pp <- rpoispp(intens)

fit <- ppm(pp ~ treatment8,  use.gam = TRUE)
fit <- ppm(pp ~ treatment8 +  spatial_covar,  use.gam = TRUE)
fit <- ppm(pp ~ treatment8 +  s(x,y, bs = 'gp', k = 40),  use.gam = TRUE)
```
###########################
## CONTINUOUS TREATMENTS ##
###########################

```{r}
## treatment is spatial covar plus a residual surface

treatment9 <- as.im(treatment7t, window)

residual_process_noisy <- RFsimulate(RMmatern(1.2, var = 0.8, scale = 0.7) + RMnugget(var = 0.3), gridx, gridx)
treatment10t <- as.im(as.matrix(residual_process_noisy), window) + spatial_covar
plot(as.im(treatment10t, window))
plot(treatment9)
intens <- exp(intercept + treatment9 + spatial_covar)
pp <- rpoispp(intens)

fit <- ppm(pp ~ treatment9,  use.gam = TRUE)
fit <- ppm(pp ~ treatment9 +  spatial_covar,  use.gam = TRUE)
fit <- ppm(pp ~ treatment9 +  s(x,y, bs = 'gp', k = 40),  use.gam = TRUE)


## realistic and potentially advantageous scenario
## we have a continuous treatment generated as a function of space, but spatial confounders have discontinuities due to geographical features
sim_surface <- function(){
    im <- as.function(as.im(as.matrix(RFsimulate(RMmatern(nu = 1, var = 2, scale = 1), gridx, gridx))))

}
s <- map(1:4, ~sim_surface())
## determine data generation mechanism
## pick optimal model from candidate model set according to specified criteria
## calculate truth value of specified estimand under dgp
## generate data
## calculate estimator values on data

## aggregate estimator values
## calculate summary statistics on estimators
## combine summary statistics across simulations for comparisons

indexer <- function(x,y) allegheny$region[as.numeric(alltessf(x,y))]
indexed <- as.im(indexer, window)

partials <- map(1:4, function(i)as.im(function(x,y) s[[i]](x,y) * (indexer(x,y) == i), window))
broken_covar <- reduce(partials, `+`)

plot(broken_covar)

```
